service: tezos-estimator
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    PRIVATE_KEY: ${env:PRIVATE_KEY}
    CONTRACT_ADDRESS: ${env:CONTRACT_ADDRESS}

functions:
  getContractMethods:
    handler: handler.getContractMethods
    events:
      - httpApi:
          path: /contractMethods
          method: get
  estimateGas:
    handler: handler.estimateGasForMethod
    events:
      - httpApi:
          path: /estimateGas
          method: post

plugins:
  - serverless-esbuild
  - serverless-offline
