service: tezos-estimator
frameworkVersion: "3"
useDotenv: true

custom:
  serverlessSsmFetch:
    PRIVATE_KEY: /tezos/estimator/private_key

provider:
  name: aws
  runtime: nodejs16.x
  profile: discord-bot
  environment:
    PRIVATE_KEY: ${env:PRIVATE_KEY}

functions:
  getContractMethods:
    handler: handler.getContractMethods
    events:
      - httpApi:
          path: /contractMethods
          method: post
  estimateGas:
    handler: handler.estimateGasForMethod
    events:
      - httpApi:
          path: /estimateGas
          method: post

plugins:
  - serverless-esbuild
  - serverless-offline
